name: "Multi-event pipeline / workflow"  # Name of the workflow/pipeline

on:      
    push:     # Whenever a push is made to the repository of the master/test branch
        branches:
            - master
            - test
    pull_request:  # Event : Whenever a pull is made to the repository
        branches:
            - master
        types:
            - closed
            - opened
    workflow_dispatch:

jobs:
    on-push:  # Job 1
        if: github.event_name == 'push'
        runs-on: windows-latest
        steps: # Steps to be executed in the job
          - name: "Running on master/test push"
            run: echo "Running on master/test push"

    on-pull-request:  # Job 2
        if: github.event_name == 'pull_request'
        runs-on: windows-latest
        steps: # Steps to be executed in the job
          - name: "Running on pull request" 
            run: echo "Running on pull request"

    on-pull-request-closed:  # Job 3
        if: github.event_name == 'pull_request' && github.event.action =='closed'
        runs-on: windows-latest
        steps: # Steps to be executed in the job
          - name: "Running on pull request closed" 
            run: echo "Running on pull request closed"

    on-workflow-dispatch:  # Job 4
        if: github.event_name == 'workflow_dispatch'
        runs-on: windows-latest
        steps: # Steps to be executed in the job
          - name: "Running on workflow dispatch" 
            run: echo "Running on workflow dispatch"

