name: "Multi-event pipeline / workflow"  # Name of the pipeline

on:      
    push:     # Whenever a push is made to the repository of the master/test branch
        branches:
            - master
            - test
    pull_request:  # Event : Whenever a pull is made to the repository
        branches:
            - master

jobs:
    on-push:  # Job-name
        runs-on: windows-latest
        steps: # Steps to be executed in the job
          - name: "Running on master/test push"
            run: echo "Running on master/test push"

    on-pull-request:  # Job-name
        runs-on: windows-latest
        steps: # Steps to be executed in the job
          - name: "Running on pull request" 
            run: echo "Running on pull request"

